---
version: '3'
services:

# START SERVICE vcwc/elastic/kibana
  kibana:
    image: ${VCW_REGISTRY}kibana:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200','SERVER_BASEPATH=/${VCW_STACK_GLOBAL_URLPREFIX}/kibana', 'XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false', 'LOGGING_VERBOSE=false']
    command: []
    volumes: []
    ports: [${VCW_STACK_KIBANA_PORTS}]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_KIBANA_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/kibana

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
