#!/usr/bin/env bash

# set CLUSTERNODE if host hostname file is mapped
CLUSTERNODE=$(< /etc/hostname)
if [[ -d /hostfs/etc ]] ; then CLUSTERNODE="linuxkit"; fi
if [[ -f /hostfs/etc/hostname ]]; then  CLUSTERNODE=$(< /hostfs/etc/hostname); fi
if [[ "${CLUSTERNODE}" == "" ]]; then CLUSTERNODE="not-set"; fi

if [[ "$@" != "" ]] ; then $@;
elif [[ -f /vcw/pwd/metricbeat.yml ]] ; then /usr/local/bin/docker-entrypoint -e -strict.perms=false -E name="${CLUSTERNODE}" -c "/vcw/pwd/metricbeat.yml";
else /usr/local/bin/docker-entrypoint -e -strict.perms=false -E name="${CLUSTERNODE}"; fi
