#!/usr/bin/env bash

prefix="vcwc_elastic_heartbeat__$1"
prefix="vcwc_elastic_heartbeat__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_elastic_heartbeat__heartbeat_heartbeat_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_heartbeat__heartbeat_heartbeat_config"
		result=$(docker volume ls | grep "vcwc_elastic_heartbeat__heartbeat_heartbeat_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_elastic_heartbeat__heartbeat_heartbeat_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_heartbeat__heartbeat_heartbeat_data_volume"
		result=$(docker volume ls | grep "vcwc_elastic_heartbeat__heartbeat_heartbeat_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_elastic_heartbeat__heartbeat_heartbeat_monitors_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_heartbeat__heartbeat_heartbeat_monitors_volume"
		result=$(docker volume ls | grep "vcwc_elastic_heartbeat__heartbeat_heartbeat_monitors_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
