#!/usr/bin/env bash

prefix="vcwc_elastic_search_rest__$1"
prefix="vcwc_elastic_search_rest__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_elastic_search_rest__api_rest_elasticsearch_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_search_rest__api_rest_elasticsearch_data_volume"
		result=$(docker volume ls | grep "vcwc_elastic_search_rest__api_rest_elasticsearch_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
