---
version: '3'
services:

# START SERVICE vcwc/elastic/search
  elasticsearch:
    image: ${VCW_REGISTRY}elasticsearch:7.9.2
    environment: ['cluster.name=elasticsearch', 'bootstrap.memory_lock=true', ES_JAVA_OPTS=-Xms${VCW_STACK_EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xmx${VCW_STACK_EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}, 'discovery.type=single-node']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume:/usr/share/elasticsearch/data']
    ports: [${VCW_STACK_EKA_ELASTICSEARCH_MODULE_ELASTICSEARCH_PORT}:9200]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_EKA_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_EKA_ELASTICSEARCH_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/search

# START SERVICE vcwc/elastic/kibana
  kibana:
    image: ${VCW_REGISTRY}kibana:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200','SERVER_BASEPATH=${VCW_STACK_EKA_KIBANA_MODULE_KIBANA_SERVER_BASEPATH}', 'XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false', 'LOGGING_VERBOSE=${VCW_STACK_EKA_KIBANA_MODULE_KIBANA_LOGGING_VERBOSE}']
    command: []
    volumes: []
    ports: [${VCW_STACK_EKA_KIBANA_MODULE_KIBANA_PORT}:5601]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_EKA_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_EKA_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_EKA_KIBANA_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/kibana

# START SERVICE vcwc/elastic/apm_server
  apm_server:
    image: ${VCW_REGISTRY}docker.elastic.co/apm/apm-server:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200']
    command: []
    volumes: []
    ports: [${VCW_STACK_EKA_APM_SERVER_MODULE_APM_SERVER_PORT}:8200]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${VCW_STACK_EKA_APM_SERVER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${VCW_STACK_EKA_APM_SERVER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${VCW_STACK_EKA_APM_SERVER_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/apm_server

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}

