---
version: '3'
services:

# START SERVICE vcwc/elastic/search
  elasticsearch:
    image: ${VCW_REGISTRY}elasticsearch:7.9.2
    environment: ['cluster.name=elasticsearch', 'bootstrap.memory_lock=true', ES_JAVA_OPTS=-Xms${ELASTIC_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xmx${ELASTIC_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}, 'discovery.type=single-node']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume:/usr/share/elasticsearch/data']
    ports: [${ELASTIC_PORTS_ELASTICSEARCH_PORT}:9200]
    networks: [${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${ELASTIC_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${ELASTIC_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'
${ELASTIC_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/search

networks: {${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}
