#!/usr/bin/env bash

prefix="vcw_module_vcwc_elastic_stacks_ekg_traefik__$1"
prefix="vcw_module_vcwc_elastic_stacks_ekg_traefik__$1"

if [[ "vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_elasticsearch_volume
fi

if [[ "vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_grafana_volume
fi

if [[ "vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_elasticsearch_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_elasticsearch_volume:/usr/share/elasticsearch/data ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/elastic/stacks/ekg/traefik/_module/volumes/ekg_elasticsearch_volume.tar
fi

if [[ "vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_grafana_volume" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_elastic_stacks_ekg_traefik__ekg_grafana_volume:/var/lib/grafana ${VCW_REGISTRY}vcwc/controlplane.vcw console untar /source/vcwc/elastic/stacks/ekg/traefik/_module/volumes/ekg_grafana_volume.tar
fi
