---
version: '3'
services:

# START SERVICE vcwc/elastic/search/traefik
  elasticsearch:
    image: ${VCW_REGISTRY}elasticsearch:7.9.2
    environment: ['cluster.name=elasticsearch', 'bootstrap.memory_lock=true', ES_JAVA_OPTS=-Xms${EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY} -Xmx${EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}, 'discovery.type=single-node']
    command: []
    volumes: ['${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume:/usr/share/elasticsearch/data']
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${EKA_ELASTICSEARCH_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${EKA_ELASTICSEARCH_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay,
      "traefik.http.middlewares.${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch.stripprefix.prefixes=/${VCW_STACK_GLOBAL_URLPREFIX}/elasticsearch,/${VCW_STACK_GLOBAL_URLPREFIX}/elasticsearch/",
      traefik.http.services.${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch.loadbalancer.server.port=9200,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch.middlewares=${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch@docker,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch.entrypoints=conteco,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch.rule=PathPrefix("/${VCW_STACK_GLOBAL_URLPREFIX}/elasticsearch") ]
${EKA_ELASTICSEARCH_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/search/traefik

# START SERVICE vcwc/elastic/kibana/traefik
  kibana:
    image: ${VCW_REGISTRY}kibana:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200','SERVER_BASEPATH=/${VCW_STACK_GLOBAL_URLPREFIX}/kibana', 'XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED=false', 'LOGGING_VERBOSE=${EKA_KIBANA_MODULE_KIBANA_LOGGING_VERBOSE}']
    command: []
    volumes: []
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${EKA_KIBANA_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${EKA_KIBANA_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay,
      "traefik.http.middlewares.${VCW_STACK_GLOBAL_STACKPREFIX}_kibana.stripprefix.prefixes=/${VCW_STACK_GLOBAL_URLPREFIX}/kibana,/${VCW_STACK_GLOBAL_URLPREFIX}/kibana/",
      traefik.http.services.${VCW_STACK_GLOBAL_STACKPREFIX}_kibana.loadbalancer.server.port=5601,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_kibana.middlewares=${VCW_STACK_GLOBAL_STACKPREFIX}_kibana@docker,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_kibana.entrypoints=conteco,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_kibana.rule=PathPrefix("/${VCW_STACK_GLOBAL_URLPREFIX}/kibana") ]
${EKA_KIBANA_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/kibana/traefik

# START SERVICE vcwc/elastic/apm_server/traefik
  apm_server:
    image: ${VCW_REGISTRY}docker.elastic.co/apm/apm-server:7.9.2
    environment: ['ELASTICSEARCH_HOSTS=http://elasticsearch:9200']
    command: []
    volumes: []
    ports: []
    networks: [${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay]
    deploy:
      mode: replicated
      resources:
        limits:
          memory: '${EKA_APM_SERVER_DEPLOY_RESOURCES_LIMITS_MEMORY}'
        reservations:
          memory: '${EKA_APM_SERVER_DEPLOY_RESOURCES_RESERVATIONS_MEMORY}'

      labels: [traefik.enable=true,traefik.docker.network=${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay,
      "traefik.http.middlewares.${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server.stripprefix.prefixes=/${VCW_STACK_GLOBAL_URLPREFIX}/apm_server,/${VCW_STACK_GLOBAL_URLPREFIX}/apm_server/",
      traefik.http.services.${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server.loadbalancer.server.port=8200,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server.middlewares=${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server@docker,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server.entrypoints=conteco,
      traefik.http.routers.${VCW_STACK_GLOBAL_STACKPREFIX}_apm_server.rule=PathPrefix("/${VCW_STACK_GLOBAL_URLPREFIX}/apm_server") ]
${EKA_APM_SERVER_COMPOSE_EXTENSIONS}
# END SERVICE vcwc/elastic/apm_server/traefik

networks: {${VCW_STACK_GLOBAL_NETWORKGLOBAL}_overlay: { external: true }, ${VCW_STACK_GLOBAL_NETWORKLOCAL}_overlay: { external: true }}
volumes: {${VCW_STACK_GLOBAL_STACKPREFIX}_elasticsearch_volume: { external: true }}
${VCW_STACK_GLOBAL_COMPOSE_EXTENSIONS}

