#!/usr/bin/env bash

prefix="vcw_module_vcwc_elastic_journalbeat__$1"
prefix="vcw_module_vcwc_elastic_journalbeat__$1"

if [[ "vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_config
fi

if [[ "vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_volume
fi

if [[ "vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_config" == "$prefix"* ]] ; then
	executionplane --silent docker run -v vcw_controlplane_repos:/source -v vcw_module_vcwc_elastic_journalbeat__ingest_journal_journalbeat_config:/vcw/pwd ${VCW_REGISTRY}vcwc/controlplane.vcw console cmd cp -r /source/vcwc/elastic/journalbeat/_module/volumes/ingest_journal_journalbeat_config/* /vcw/pwd
fi
