#!/usr/bin/env bash

prefix="vcwc_elastic_filebeat_file__$1"
prefix="vcwc_elastic_filebeat_file__$1"

executionplane --silent docker container prune --force

if [[ "vcwc_elastic_filebeat_file__filebeat_filebeat_data_volume" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_filebeat_file__filebeat_filebeat_data_volume"
		result=$(docker volume ls | grep "vcwc_elastic_filebeat_file__filebeat_filebeat_data_volume")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi

if [[ "vcwc_elastic_filebeat_file__filebeat_filebeat_config" == "$prefix"* ]] ; then
	continue="true"
	while [[ "true" == "$continue" ]] ;
	do
		executionplane docker volume rm "vcwc_elastic_filebeat_file__filebeat_filebeat_config"
		result=$(docker volume ls | grep "vcwc_elastic_filebeat_file__filebeat_filebeat_config")
		if [[ "$result" == "" ]] ; then
			continue="false"
		else
			sleep 3;
		fi
	done;
fi
